GET http://localhost:5000/api/users/


###

POST http://localhost:5000/api/user/
Content-Type: application/json

{
"firstname": "Olivia", "lastname": "Isberg", "email": "oliviaisberg@gmail.com", "password": "hejsan"
}