GET http://localhost:5000/api/users/


###

POST http://localhost:5000/api/user/
Content-Type: application/json

{
"firstname": "Hej", "lastname": "Isberg", "email": "hej@gmail.com", "password": "hejsan"
}